"""empty message

Revision ID: 20423f971072
Revises: bba75f5aaffe
Create Date: 2022-12-09 15:01:33.826604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20423f971072'
down_revision = 'bba75f5aaffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_diameter_key', type_='unique')
        batch_op.drop_column('diameter')
        batch_op.drop_column('climate')
        batch_op.drop_column('gravity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravity', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('climate', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.VARCHAR(length=28), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('people_diameter_key', ['diameter'])

    # ### end Alembic commands ###
