"""empty message

Revision ID: 74981b215e4a
Revises: 20423f971072
Create Date: 2022-12-09 18:32:29.234487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74981b215e4a'
down_revision = '20423f971072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('PeopleId', sa.Integer(), nullable=True),
    sa.Column('planetId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['PeopleId'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planetId'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
