"""empty message

Revision ID: 991e3867ce55
Revises: 2386ce1fdf47
Create Date: 2022-12-09 01:53:59.230974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991e3867ce55'
down_revision = '2386ce1fdf47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('birth_year', sa.String(length=20), nullable=False),
    sa.Column('eye_color', sa.String(length=14), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
